services:
  digipres.dspace.lib.unb.ca:
    build:
      context: .
    restart: unless-stopped
    container_name: digipres.dspace.lib.unb.ca
    env_file:
      - ./env/dspace.env
    expose:
      - "8080"
    ports:
      - "3507:8080"
    networks:
      - digipres.dspace.lib.unb.ca
  digipres.postgres.lib.unb.ca:
    build:
      context: postgres/
    restart: unless-stopped
    env_file:
      - ./env/dspace.env
    expose:
      - "5432"
    networks:
      - digipres.dspace.lib.unb.ca
  digipres.solr.lib.unb.ca:
    build:
      context: solr/
    restart: unless-stopped
    env_file:
      - ./env/dspace.env
    expose:
      - "8080"
    networks:
      - digipres.dspace.lib.unb.ca
networks:
  digipres.dspace.lib.unb.ca:
    name: digipres.dspace.lib.unb.ca
